version: "3"

services:
    web:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: WebcoomApi
            MYSQL_USER: WebcoomApi
            MYSQL_PASSWORD: WebcoomApi
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
